export { default as AddressForm } from './views/AddressForm.svelte'
export { default as EmbeddedCheckout } from './views/EmbeddedCheckout.svelte'
export { default as InitialView } from './views/InitialView.svelte'
export { default as ZipForm } from './views/ZipForm.svelte'
export { name, address, state, zip } from './stores/customer'
export { views, unavailableViews, currentViewIndex, currentView, currentViewOverride, activeComponent } from './stores/views'
